package com.soft863.mbg.entity;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodsId
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodsName
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodsTotal
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Integer goodstotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.createTime
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.pid
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Long pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodsId
     *
     * @return the value of t_goods.goodsId
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodsId
     *
     * @param goodsid the value for t_goods.goodsId
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodsName
     *
     * @return the value of t_goods.goodsName
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodsName
     *
     * @param goodsname the value for t_goods.goodsName
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodsTotal
     *
     * @return the value of t_goods.goodsTotal
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Integer getGoodstotal() {
        return goodstotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodsTotal
     *
     * @param goodstotal the value for t_goods.goodsTotal
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setGoodstotal(Integer goodstotal) {
        this.goodstotal = goodstotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.createTime
     *
     * @return the value of t_goods.createTime
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.createTime
     *
     * @param createtime the value for t_goods.createTime
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.pid
     *
     * @return the value of t_goods.pid
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.pid
     *
     * @param pid the value for t_goods.pid
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }
}