package com.soft863.mbg.entity;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.s_id
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.stu_id
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.chinese
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Double chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.math
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Double math;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.english
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    private Double english;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.s_id
     *
     * @return the value of t_score.s_id
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.s_id
     *
     * @param sId the value for t_score.s_id
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.stu_id
     *
     * @return the value of t_score.stu_id
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.stu_id
     *
     * @param stuId the value for t_score.stu_id
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.chinese
     *
     * @return the value of t_score.chinese
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Double getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.chinese
     *
     * @param chinese the value for t_score.chinese
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setChinese(Double chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.math
     *
     * @return the value of t_score.math
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Double getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.math
     *
     * @param math the value for t_score.math
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setMath(Double math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.english
     *
     * @return the value of t_score.english
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public Double getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.english
     *
     * @param english the value for t_score.english
     *
     * @mbg.generated Wed Oct 25 15:52:58 CST 2017
     */
    public void setEnglish(Double english) {
        this.english = english;
    }
}